### ISSUE TITLE
[BUG]: Cannot read properties of undefined (reading 'row')

### ISSUE THREAD

**Issue by raphaeldas** [Fekide/strapi-plugin-translate#142]
**Describe the bug**
After updating strapi to version 4.8.2 i get the error `Cannot read properties of undefined (reading 'row')` when trying to access the plugin on the dashboard: http://localhost:1337/admin/plugins/translate

It seems the template of the page gets loaded. It's visible for a short time, then javascript throws this error and the whole page gets blank. 

**To Reproduce**
1. Update Strapi to latest version
2. Login to dashboard
3. Click **Translate** in the left sidebar
4. See error in console and page getting blank

**Expected behavior**
The overview of translatable content-types as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/15084829/225922445-812161b7-f021-4fd3-a792-de3e2d8bc11a.png)

**System:**
 - OS: both Windows 10 and Ubuntu 20.04
 - Browser brave, edge, firefox
 - Versions:
   - strapi: 4.8.2
   - strapi-plugin-translate: 1.1.1
   - provider: strapi-provider-translate-deepl@1.1.1
- Other Strapi plugins:
  - strapi-middleware-upload-plugin-cache@2.1.0
  - strapi-plugin-config-sync@1.1.1
  - strapi-plugin-populate-deep@1.1.2
  - strapi-plugin-rest-cache@4.2.6
  - strapi-plugin-transformer@3.0.1
  - strapi-prometheus@1.5.0
  - strapi-provider-rest-cache-memory@4.2.7

**Plugin config**
Please add your plugin config here, e.g.
```js
module.exports = {
	translate: {
		enabled: true,
		config: {
			provider: 'deepl',
			providerOptions: {
				apiKey: [apiKey],
				freeApi: true,
			},
			translatedFieldTypes: [
				'string',
				'text',
				'richtext',
				'component',
				'dynamiczone',
			],
			translateRelations: true
		}
	},
}
```

**Comment by layaxx** [comment]
Hi @raphaeldas,
thank you for bringing this to our attention.
I think I have identified the problem and will have a PR ready shortly.
