### ISSUE TITLE
[BUG]:  When we use translator we have a problem with bound entities

### ISSUE THREAD

**Issue by AlexandraKartashovaFusion** [Fekide/strapi-plugin-translate#161]
**Describe the bug**
When translating a page from English into German, an English category is attached to the German page

**To Reproduce**
1. Go to Germany page (already having a page with an associated category in English)
2. Click on translate from another locale & select English
3. And after we can see that for our Germany page connected Englissh category

**Expected behavior**

**Screenshots**
https://www.screencast.com/t/aRtpKpG67op

**System (please complete the following information):**
 - OS: MacOs, Windows
 - Browser  firefox, safari, chrome
 - Versions:
   - strapi:  "4.7.1"
   - strapi-plugin-translate:"1.1.1"
   - strapi-provider-translate-deepl@: "1.1.1"

**Plugin config**
module.exports = {
translate: {
enabled: true,
config: {
apiKey: process.env('DEEPL_API_KEY'),
provider: 'deepl',
providerOptions: {
apiKey: process.env('DEEPL_API_KEY'),
apiOptions: {
formality: 'prefer_less',
}
},
translateRelations: true,
glossaryId: 'customGlossary',
},
},
};

**Comment by sargreal** [comment]
Hi @AlexandraKartashovaFusion 

Can you please share the content type schemas of the translated entity and the category?
I am not able to reproduce this

**Comment by AlexandraKartashovaFusion** [comment]
@sargreal 

entity 
{
  "kind": "collectionType",
  "collectionName": "quizzes",
  "info": {
    "singularName": "quize",
    "pluralName": "quizzes",
    "displayName": "Quizzes",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "software_category": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::software-category.software-category",
      "pluginOptions": {
        "translate": {
          "translate": ""
        }
      }
    },
    "questions": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        },
        "translate": {
          "translate": "translate"
        }
      },
      "type": "dynamiczone",
      "components": [
        "quiz.black-ovals",
        "quiz.slider",
        "quiz.ovals",
        "quiz.big-boxes",
        "quiz.small-boxes",
        "quiz.redirect-slide"
      ]
    },
    "seo": {
      "type": "component",
      "repeatable": false,
      "pluginOptions": {
        "i18n": {
          "localized": true
        },
        "translate": {
          "translate": "translate"
        }
      },
      "component": "seo.seo",
      "required": true
    }
  }
}




entity category
{
  "kind": "collectionType",
  "collectionName": "software_categories",
  "info": {
    "singularName": "software-category",
    "pluralName": "software-categories",
    "displayName": "Software Categories",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "name": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        },
        "translate": {
          "translate": "translate"
        }
      },
      "type": "string",
      "minLength": 2,
      "required": true
    },
    "icon": {
      "type": "media",
      "multiple": false,
      "required": true,
      "allowedTypes": [
        "images"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      }
    },
    "description": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        },
        "translate": {
          "translate": "translate"
        }
      },
      "type": "richtext",
      "minLength": 2,
      "required": true
    },
    "backgroundColor": {
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      },
      "type": "string",
      "minLength": 2,
      "regex": "(?:#)(?:[aA-fF0-9]{3}|[aA-fF0-9]{6})",
      "required": true
    },
    "slug": {
      "type": "string",
      "pluginOptions": {
        "i18n": {
          "localized": true
        },
        "translate": {
          "translate": "translate"
        }
      },
      "regex": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
      "minLength": 2,
      "required": true
    },
    "breadcrumb": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        },
        "translate": {
          "translate": "translate"
        }
      },
      "type": "string",
      "required": true,
      "minLength": 2
    },
    "nameOfTableSubComparison": {
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      },
      "type": "string"
    },
    "lineBreakName": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        },
        "translate": {
          "translate": "translate"
        }
      },
      "type": "richtext",
      "minLength": 1
    },
    "quizId": {
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      },
      "type": "integer",
      "required": false,
      "unique": false
    }
  }
}

**Comment by sargreal** [comment]
I think I have spotted the issue @AlexandraKartashovaFusion !

In your entity schema under `attributes.software_category.pluginOptions` you have th following:
```json
"pluginOptions": {
  "translate": {
    "translate": ""
  }
}
```
The value is for some reason (that I did not yet find) an empty string, which is in the current code considered as a direct copy. It should be for your use case "translate". Other options would be "copy" or "delete". You can find the explanation for this here: https://github.com/Fekide/strapi-plugin-translate#configure-translation-of-individual-fieldsattributes

I will however create a fix that will address the default behavior
