### ISSUE TITLE
[FEATURE]: OpenAI (ChatGPT 4) provider

### ISSUE THREAD

**Issue by ricoxor** [Fekide/strapi-plugin-translate#223]
Hello,
Is there someone who already created a provider for ChatGPT v4 ?
I saw that is cheaper than Deepl and give a better translation.
Thank you

**Comment by reslear** [comment]
Why did you close, what was the solution?

**Comment by reslear** [comment]
@ricoxor  Why did you close, what was the solution?

**Comment by BenCherif** [comment]
Any update about this enhancement?

**Comment by fcsonline** [comment]
https://www.npmjs.com/package/strapi-provider-translate-chatgpt by @Braunmann
