### ISSUE TITLE
[BUG]: TypeError: d.decompose is not a function 

### ISSUE THREAD

**Issue by Shekhar-Zealous** [Fekide/strapi-plugin-translate#246]
**Describe the bug**
Another issue faced while using translate. Error is displayed in console. 
I have tried removing relationships, custom field plugins, custom components but still it didn't working after a lot of efforts.

**To Reproduce**
1. Create a default English record for collection.
2. Click on "Locale" dropdown from Action list and move to Spanish language. 
3. Then click on "Translate from another locale" from English and click "Yes, fill in" and save the record.
4. Puff, it's gone.

**Expected behavior**
The page shouldn't break and translate should happen.

**Screenshots**

https://github.com/Fekide/strapi-plugin-translate/assets/104756792/9a2b6c1b-b53f-4e45-9868-f4a0691e3476

**System (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Versions:
   - strapi: 4.9.0
   - strapi-plugin-translate:  1.1.5
   - provider: strapi-provider-translate-deepl@1.1.5

**Plugin config**
Please add your plugin config here, e.g.
```js
module.exports = {
  translate: {
    enabled: true,
    config: {
      provider: 'deepl',
      providerOptions: {
        apiKey: '*************'
      },
      translatedFieldTypes: [
        'string',
        { type: 'text', format: 'plain' },
        { type: 'richtext', format: 'markdown' },
        'component',
        'dynamiczone',
      ],
      translateRelations: true,
    },
  },
}
```

**Comment by Shekhar-Zealous** [comment]
@layaxx I check it by removing field 1 by 1, and at last I found the issue. 
The issue is appearing due to JSON fields.  Still this is a bug from the plugin side which should not be the case.
Any idea here....

**Comment by layaxx** [comment]
Hey @Shekhar-Zealous, 
I can confirm that there seems to be some issue with JSON fields, however for me it does not display the error you describe, instead strapi just kind of hangs and the tab becomes non-responsive. I will look into this. 
Could you provide additional information about your setup?
- Which version of node are you running?
- could you try if running  `yarn develop --watch-admin` gives you a more useful error message?
- which version of `@strapi/plugin-i18n` are you running (you can find out via package.json or running `yarn list --pattern @strapi/plugin-i18n`)?

**Comment by Shekhar-Zealous** [comment]
@layaxx Thank you for looking into the issue. I hope that can be fixed ASAP. 
Some of my development work is on hold due to this issue :(

- Node Version: 16.16.0
- strapi-plugin-translate: 1.1.5
- provider: strapi-provider-translate-deepl@1.1.5

After using --watch-admin, the translation feature gets hidden somehow.
![image](https://github.com/Fekide/strapi-plugin-translate/assets/104756792/392c7cc5-1cb8-40f9-9840-cc73ac68ffcc)

**Comment by Shekhar-Zealous** [comment]
Hey @layaxx, how are you?

Any update regarding the above. Have you started looking for the issue?

**Comment by layaxx** [comment]
Hey @Shekhar-Zealous,
unfortunately there is no update so far and I also cannot provide you with a timeframe for this.
I hope you understand.

**Comment by layaxx** [comment]
Did some digging and may have found the problem, at least with the problem I had encountered. Not sure whether this (https://github.com/Fekide/strapi-plugin-translate/pull/266) will fix your problem as well, though @Shekhar-Zealous

**Comment by Shekhar-Zealous** [comment]
@layaxx Hope this will fix the issue once your PR is accepted and released.
Thank you :)
