### ISSUE TITLE
Strapi 4.5 support

### ISSUE THREAD

**Issue by willempie96** [Fekide/strapi-plugin-translate#35]
When using this plugin in combination with strapi 4.5.x i cant use the translate form different locale feature in the content manager.
I traced the problem to the new way of (lazy) loading relations. This means that the data in the admin ui doesn't standard have the id's of the relations resulting in an error when trying to translate:

```
error: Translating entity failed: Undefined binding(s) detected when compiling WHERE. Undefined column(s): [t0.id] query: where `t0`.`id` = ?
```

Are you going to offer strapi 4.5 support?

**Comment by sargreal** [comment]
@willempie96 Thank you for pointing this out!

Fix is in progress, it is much harder than expected.

In the meantime you can use the Batch Translation
