### ISSUE TITLE
Automate Translation and Publishing on New Localization Addition

### ISSUE THREAD

**Issue by hadiulofficial** [Fekide/strapi-plugin-translate#426]
I want to automate the translation process whenever a new localization is added in the Strapi dashboard. Specifically, I would like the "Translate" button to be automatically triggered to translate and publish the content whenever a new language is added. 

Could you please guide me on how to achieve this automation using the Strapi Translate Plugin?

![image](https://github.com/user-attachments/assets/d91e9cb8-7ec5-4ed7-998e-a1d3dd22c0e9)
![image](https://github.com/user-attachments/assets/517683a5-c12c-4c12-9866-48528a60affe)

**Comment by sargreal** [comment]
Hi @hadiulofficial!

Thank you for your question. Your request is similar to #284
Please take inspiration and ask more questions there. We will improve the documentation and service api to make this easier at some point, possibly making this an automated process.
