### ISSUE TITLE
[BUG]: Translate plugin not working with multiple Editors.

### ISSUE THREAD

**Issue by thewickest** [Fekide/strapi-plugin-translate#427]
**Describe the bug**
The translate plugin is not working with multiple dynamic component (ex.: more than one Rich Text editor). If you have a dynamic component inside an Type and you add many components of that type, only the first component it's translated. 

**To Reproduce**

1. Create a Type with a Dynamic Section
2. Inside that Dynamic Section add the Rich Text Editor component from Strapi
3. Add content to that Type with many Rich Text Editors
4. Translate the Type to another language with the plugin
5. In the translated Type, you will see that only the first module it's translated

**Expected behavior**
Every module should be translated.

**System (please complete the following information):**

- OS: MacOs Ventura 13.6.7
- Browser: N/A
- Versions:
  - strapi: 4.22
  - strapi-plugin-translate: 1.2.4
  - provider: strapi-provider-translate-deepl

**Comment by sargreal** [comment]
Thank you @thewickest for opening this issue!

I have tried to reproduce this issue with your provided details, however I do not see the same behavior. 
Can you please either
- share the exact content type and component schemas or 
- create a new public repository with a simple strapi environment where you can reproduce the issue
