### ISSUE TITLE
 error: Translating entity failed: Request failed with status code 400

### ISSUE THREAD

**Issue by angautamgitops** [Fekide/strapi-plugin-translate#43]
I am trying to set up deepl plugin for automated translation. followed the doc - https://market.strapi.io/plugins/strapi-plugin-deepl#configuration for the set up however there is no luck. I even tried to register with paid version but the moment i do translate from other locale under content-management I get a warning : Bad request to Deepl Api and in logs - translating entity failed: Request failed with status code 400 . It seems a configuration issue from the Strapi end.. could you please advise?

Below is the error printed in logs.

[2023-01-06 14:31:12.401] error: Translating entity failed: Request failed with status code 400
[2023-01-06 14:31:12.402] http: POST /deepl/translate (223 ms) 400

**Comment by sargreal** [comment]
Hi @angautamgitops 

I have just installed the plugin from scratch and found no issues. could you please elaborate more on your environment?
- What strapi version are you using?
- What is the version of the DeepL plugin?
- What other plugins are you using?
- Is there anything special about the content type you are translating i.e. are there custom fields involved?

As for the configuration: could you please share the configuration portion of the deepl plugin (obviously with the api key redacted)?

**Comment by sargreal** [comment]
> glossaryId: 'customGlossary',

I think this is the issue: you need to uncomment this line in the configuration as you probably do not have a custom Glossary set up

**Comment by angautamgitops** [comment]
Thank you very much, after commenting out, it's working now. Have a nice weekend.!
