### ISSUE TITLE
[BUG]: Cannot read properties of null (reading '__component')

### ISSUE THREAD

**Issue by bkrajewski94** [Fekide/strapi-plugin-translate#472]
**Describe the bug**
I see an error Cannot read properties of null (reading '__component') when I try to translate pages and components after upgrading to 1.2.6

**To Reproduce**
Not sure what it's caused by, I just hit the translate button and try to retranslate, the way I did on 1.2.5. I see an error:
```
main.1ecca1de.js:1211 TypeError: Cannot read properties of null (reading '__component')
    at xe (main.1ecca1de.js:1200:9807)
    at main.1ecca1de.js:1200:10180
    at Array.forEach (<anonymous>)
    at xe (main.1ecca1de.js:1200:9977)
    at main.1ecca1de.js:1200:10292
    at Array.map (<anonymous>)
    at main.1ecca1de.js:1200:10279
    at Array.forEach (<anonymous>)
    at xe (main.1ecca1de.js:1200:9977)
    at _n (main.1ecca1de.js:1211:1677)
```

**Screenshots**
Source code of error in the console:
![image](https://github.com/user-attachments/assets/f2b733de-24a5-46ad-a2e4-ae5d47ebe8fc)

**System (please complete the following information):**

- OS: macos
- Browser chrome
- Versions:
```
  "dependencies": {
    "@ckeditor/strapi-plugin-ckeditor": "^0.0.10",
    "@strapi/plugin-i18n": "^4.25.16",
    "@strapi/plugin-users-permissions": "^4.25.16",
    "@strapi/provider-email-nodemailer": "^4.25.16",
    "@strapi/strapi": "^4.25.16",
    "logger": "1.0.0",
    "mysql": "^2.18.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^5.2.0",
    "strapi-plugin-public-permissions": "^0.2.2",
    "strapi-plugin-translate": "^1.2.6",
    "strapi-provider-translate-deepl": "^1.1.14",
    "strapi-provider-upload-bunnynet": "1.0.0",
    "styled-components": "^5.2.1"
  },
```

**Plugin config**
```js
  translate: {
    enabled: true,
    config: {
      translatedFieldTypes: [
        { type: 'string', format: 'plain' },
        { type: 'text', format: 'plain' },
        { type: 'richtext', format: 'html' },
        'component',
        'dynamiczone',
      ],
      provider: 'deepl',
      providerOptions: {
        apiKey: env('DEEPL_API_KEY'),
        localeMap: {
          EN: 'EN-US',
        },
        apiOptions: {
          formality: 'default',
        },
      },
    },
  },
```

**Additional context**
My data is deeply nested (more than 2 levels)

**Comment by bkrajewski94** [comment]
Hi @sargreal. I've nailed down the problem. Look here:
https://www.loom.com/share/c80ea463171445959d3688de1e647024?sid=76458bb0-be47-4091-a4a1-c8cc76a64b37

**Comment by bkrajewski94** [comment]
Basically it fails when component value is not set (even if it's not required). Not sure if this is the only case though

**Comment by sargreal** [comment]
> Hi @sargreal. I've nailed down the problem. Look here: https://www.loom.com/share/c80ea463171445959d3688de1e647024?sid=76458bb0-be47-4091-a4a1-c8cc76a64b37
> 
> Basically it fails when component value is not set (even if it's not required). Not sure if this is the only case though

Thank you @bkrajewski94, i have actually found this reason as well just now. PR #474 should fix this
