### ISSUE TITLE
Error saying targetLang='en' is deprecated, please use 'en-GB' or 'en-US' instead

### ISSUE THREAD

**Issue by adriaanvanrossum** [Fekide/strapi-plugin-translate#62]
When translating from a non-English locale to English, I get this error.

> targetLang='en' is deprecated, please use 'en-GB' or 'en-US' instead.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/1079135/212887693-6b874287-4235-4a28-81f8-8cce2eaf871c.png">

Versions: 

```json
{
  "dependencies": {
    "@strapi/plugin-i18n": "4.5.6",
    "@strapi/plugin-users-permissions": "4.5.6",
    "@strapi/strapi": "4.5.6",
    "better-sqlite3": "7.4.6",
    "pg": "8.6.0",
    "strapi-plugin-translate": "^1.0.0",
    "strapi-provider-translate-deepl": "^1.0.0"
  }
}
```

**Comment by lauridskern** [comment]
getting the same error

**Comment by adriaanvanrossum** [comment]
> You can fix this by adding the locale en-US and removing the en locale.

Indeed, but you can't change locale. We have everything in `en` instead of `en-US`. We could copy every content piece we have, but it's a lot of work.

**Comment by sargreal** [comment]
That is unfortunate, since it is only deprecated I had not expected it to throw an error.

@adriaanvanrossum What locale would you then prefer for `en`? `en-GB` or `en-US`?

**Comment by adriaanvanrossum** [comment]
Yes indeed. For us `en-US` would be best as it cover more of our customers.
