### ISSUE TITLE
How i can set formality?

### ISSUE THREAD

**Issue by AlexandraKartashovaFusion** [Fekide/strapi-plugin-translate#70]
Hi,

Ш need to set the  "formality: prefer_less" so that the language is less formative. 
Рow can i do this using this plugin in strapi?

**Comment by layaxx** [comment]
Hi, this is not yet possible, but should not be too hard to implement.
I will look into it

**Comment by AlexandraKartashovaFusion** [comment]
> Hi, this is not yet possible, but should not be too hard to implement. I will look into it

Hi.
Any news about issue?

**Comment by sargreal** [comment]
@AlexandraKartashovaFusion This has been implemented and will be released in version 1.1
