### ISSUE TITLE
Saving entity after translating not possible in strapi 4.5.x

### ISSUE THREAD

**Issue by sargreal** [Fekide/strapi-plugin-translate#74]
After translating an entity directly from another locale, it is not possible to save the entity.

The following call stack is displayed in the console when in `watch-admin` mode:
```
TypeError
error.response is undefined
Call Stack
 getAPIInnerErrors
  lib/src/utils/getAPIInnerErrors/index.js:6:24
 EditViewDataManagerProvider/handleSubmit
  webpack-internal:///69413:377:133
 fulfilled
  webpack-internal:///69413:56:24
 promise callback*step
  webpack-internal:///69413:68:76
 __async/<
  webpack-internal:///69413:69:9
 __async
  webpack-internal:///69413:53:10
 EditViewDataManagerProvider/handleSubmit<
  webpack-internal:///69413:359:19
 callCallback
  webpack-internal:///63464:3946:14
 invokeGuardedCallbackDev
  webpack-internal:///63464:3995:16
 invokeGuardedCallback
  webpack-internal:///63464:4057:31
```

Source of the bug currently unknown. Affected strapi versions at least 4.5.6 possibly earlier ones as well

**Comment by JonasGruenwald** [comment]
I'm not sure if this is the same issue, but I noticed that if I have a component, dynamic zone or relation field set to anything other than Delete (So translate which is the default, or Copy), I cannot save the entity and there is some frontend error in the console.
Not sure if that's the same issue.
After setting all these fields to delete I can save entries in 4.5.6

**Comment by JonasGruenwald** [comment]
I'm trying to look into this but I can't seem to understand how the plugin sets relations in the frontend, I saw that strapi internally calls `onChange` from the EditViewDataManager to update regular fields and `connectRelation` (or `relationConnect` after a recent refactor) to update connection fields after a relation is selected in the UI, but I don't see the plugin calling the relation connection functions anywhere, only `onChange`, how are the relations supposed to be set?

**Comment by sargreal** [comment]
> I'm trying to look into this but I can't seem to understand how the plugin sets relations in the frontend, I saw that strapi internally calls `onChange` from the EditViewDataManager to update regular fields and `connectRelation` (or `relationConnect` after a recent refactor) to update connection fields after a relation is selected in the UI, but I don't see the plugin calling the relation connection functions anywhere, only `onChange`, how are the relations supposed to be set?

In think we have found the issue, it’s that the relationinput expects an array and not an object. If you want you can open a pr, I will not be able to code the next few days
