### ISSUE TITLE
Translated document won't save and throws error

### ISSUE THREAD

**Issue by anatolykopyl** [Fekide/strapi-plugin-translate#78]
If a document has a `hasOne` relation that is set to `translate`, then it will not be translated. Said document will not be able to save and will throw the following error in the console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at qc (main.96060888.js:13200:3220)
    at content-manager.9fb36cc0.chunk.js:9856:140
    at Generator.next (<anonymous>)
    at fulfilled (content-manager.9fb36cc0.chunk.js:9534:24)
```

Here's a reproduction repo: https://github.com/anatolykopyl/plugin-translate-reproduction

https://user-images.githubusercontent.com/33553182/214669996-d92daff7-2403-4275-9b5a-f331f3306d66.mp4

**Comment by sargreal** [comment]
Probably connected to #74 although the error is different

**Comment by Shekhar-Zealous** [comment]
This issue exists in latest version 1.1.5 @fekide-bot 
![image](https://github.com/Fekide/strapi-plugin-translate/assets/104756792/57be8c3a-3f09-4481-aefd-78e0f9cd9d29)
